version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - apt-get install -y unzip

  build:
    commands:
      - echo "Listing files in S3 path..."
      - aws s3 ls s3://codepipeline-ap-south-1-617832984535/ecommerce-app/SourceArti/ --recursive
      - FILE_NAME=$(aws s3 ls s3://codepipeline-ap-south-1-617832984535/ecommerce-app/SourceArti/ --recursive | sort | tail -n 1 | awk '{print $4}')
      - echo "FILE_NAME is: $FILE_NAME"  # Check if it's being set correctly
      - if [ -z "$FILE_NAME" ]; then echo "No files found in S3 path"; exit 1; fi
      - echo "Latest file is $FILE_NAME"
      - aws s3 cp s3://codepipeline-ap-south-1-617832984535/$FILE_NAME ./myapp.zip
      - echo "Unzipping the source artifact..."
      - unzip myapp.zip -d extracted_files1/
      - echo "Build process..."

  post_build:
    commands:
      - echo "Build complete"
      - echo "Creating build artifacts..."
      - mkdir -p extracted_files
      - echo "Cleaning up..."
      - rm -rf extracted_files

artifacts:
  files:
    - '**/*'
  base-directory: extracted_files1
  discard-paths: yes
